name: Build and deploy Node.js app to Azure Web App - patel-ceramics-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: Backend          # run everything inside Backend/

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: Backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (if present)
        run: npm run build --if-present

      # 🔥 removed the failing test step

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: Backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8A7664E40BB547CDABE8E7EF12E24E4E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7DEEFD971494167B3302CBBB62740BC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4ED22B3277F641608F3B251B6F7CB18C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'patel-ceramics-api'
          slot-name: 'Production'
          package: 'Backend'                 # deploy Backend folder
